language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - source activate pz
  - pip install .
  - mkdir somewhere_else
  - cd somewhere_else

script:
  - python -V
  - python -c "import protozfitsreader"
  - python -c "from protozfitsreader import rawzfitsreader"
  - python -c "from protozfitsreader import rawzfitsreader; print(rawzfitsreader.__file__)"

