language: generic
os:
  - linux
  - osx
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

matrix:
  include:
    - os: linux
      python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: osx
      python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - os: osx
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

install:
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n pz python=$PYTHON_VERSION pip numpy protobuf pytest
  - source activate pz
  - pip install .

script:
  - pytest -vv
  - echo "trying to show, that deinstall works"
  - cd  /home/travis
  - find . | grep "rawzfitsreader.cpython-35m-x86_64-linux-gnu.so"
  - pip uninstall protozfitsreader --yes
  - find . | grep "rawzfitsreader.cpython-35m-x86_64-linux-gnu.so"




